In [1]:
import pandas as pd
# from data_dicts import education_columns, age_sex_columns, race_columns, income_columns

from data_dicts_values import drop_cols, edu_cols_2012
from data_prep_values import county_info_2012, county_info_2016, county_info_2018, results_info, create_targets
from model_prep import lin_mod_func, run_model, make_predictions, combine_predictions
from visualizations import display_results

In [2]:
features_2012 = county_info_2012()
features_2016 = county_info_2016()
features_2018 = county_info_2018()
results_2012 = results_info(2012)
results_2016 = results_info(2016)

In [3]:
# 'Total!!Estimate!!Less than 9th grade'

In [8]:
df = pd.DataFrame(features_2012.State.unique().tolist())

In [9]:
df

                       0
0               Arkansas
1             California
2               Colorado
3            Connecticut
4               Delaware
5                Florida
6                Georgia
7                Alabama
8                 Alaska
9                Arizona
10                Kansas
11              Kentucky
12             Louisiana
13                 Maine
14              Maryland
15         Massachusetts
16              Michigan
17             Minnesota
18                Hawaii
19                 Idaho
20              Illinois
21               Indiana
22                  Iowa
23           Mississippi
24              Missouri
25               Montana
26        North Carolina
27          North Dakota
28                  Ohio
29              Oklahoma
30                Oregon
31          Pennsylvania
32          Rhode Island
33        South Carolina
34              Nebraska
35                Nevada
36         New Hampshire
37            New Jersey
38            New Mexico
39              New York
40                 Texas
41                  Utah
42               Vermont
43              Virginia
44            Washington
45         West Virginia
46             Wisconsin
47               Wyoming
48           Puerto Rico
49          South Dakota
50             Tennessee
51  District of Columbia

In [5]:
df = pd.merge(features_2012, results_2012, on='County')
df = df.drop(columns = 'State_y')
df = df.rename(columns={'State_x': 'State'})
#df = create_targets(df)

In [6]:
df

,County,State,Total population,Median age,Sex ratio (males per 100 females),Male Median age,Female Median age,Total White,Total Black or African American,Total American Indian and Alaska Native,...,Total Less than 9th grade,"Total 9th to 12th grade, no diploma",Total High school graduate,"Total Some college, no degree",Total Associate's degree,Total Bachelor's degree,Total Graduate or professional degree,Republican,Democrat,Other
0,"Perry County, Arkansas, 2012",Arkansas,10413,42.1,99.0,40.7,43.1,43841,10126,523,...,697.671,1176.669,3988.179,2405.403,499.824,676.845,333.216,2581,1187,170
1,"Phillips County, Arkansas, 2012",Arkansas,21646,37.3,88.1,34.4,39.7,160739,18164,2584,...,2142.954,3701.466,5238.332,4350.846,2034.724,1904.848,952.424,2598,5202,130
2,"Pike County, Arkansas, 2012",Arkansas,11261,39.8,100.5,37.1,41.9,13816,12993,368,...,731.965,1700.411,3355.778,2657.596,585.572,889.619,506.745,2847,851,90
3,"Poinsett County, Arkansas, 2012",Arkansas,24506,39.6,94.2,38.2,40.7,17661,5171,131,...,2793.684,3847.442,10978.688,4362.068,1004.746,1470.360,710.674,4974,2390,196
4,"Polk County, Arkansas, 2012",Arkansas,20535,43.4,95.8,42.3,44.7,55359,1023,710,...,1191.030,2361.525,8583.630,5359.635,1416.915,1622.265,780.330,5955,1556,215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3058,"Montague County, Texas, 2012",Texas,19737,42.6,96.9,40.8,44.4,16349,1275,129,...,1282.905,2230.281,9671.130,5407.938,1263.168,2151.333,809.217,6549,1116,86
3059,"Montgomery County, Texas, 2012",Texas,458339,36.2,98.3,35.2,37.0,6111,566,15,...,25666.984,39417.154,154460.243,112751.394,30708.713,96251.190,42167.188,137969,32920,2224
3060,"Moore County, Texas, 2012",Texas,21765,30.8,104.6,29.4,31.7,30934,9152,512,...,3852.405,3025.335,4178.880,4374.765,1197.075,2002.380,870.600,3968,964,53
3061,"Morris County, Texas, 2012",Texas,12914,43.0,92.5,41.1,44.5,144673,69450,2491,...,826.496,1536.766,3732.146,2879.822,1149.346,1201.002,723.184,3232,1858,49
3062,"Washington city County, District of Columbia, ...",District of Columbia,605759,33.9,89.7,33.7,34.1,248485,316435,5007,...,29076.432,46643.443,125997.872,86623.537,17567.011,136295.775,173852.833,21381,267070,5313

In [9]:
df['Total Less than 9th grade'].max()

38.2

In [5]:
df_edu = pd.read_csv('data/2012/2012-Edu/ACSST5Y2012.S1501_data_with_overlays_2020-01-21T124942.csv',
                         header=1, low_memory=False)
df_age_sex = pd.read_csv('data/2012/2012-Age/ACSST5Y2012.S0101_data_with_overlays_2020-01-21T124608.csv',
                             header=1, low_memory=False)
df_race = pd.read_csv('data/2012/2012-Race/ACSDP5Y2012.DP05_data_with_overlays_2020-01-21T125225.csv',
                          header=1, low_memory=False)
df_income = pd.read_csv('data/2012/2012-Income/ACSST5Y2012.S1901_data_with_overlays_2020-01-21T124756.csv',
                            header=1, low_memory=False)

In [6]:
"Total!!Estimate!!Population 25 years and over!!Less than 9th grade"
'Total!!Estimate!!Less than 9th grade'
'Total!!Estimate!!Less than high school graduate'

'Total!!Estimate!!Less than high school graduate'

In [7]:
df_edu.columns.tolist()

['id',
 'Geographic Area Name',
 'Total!!Estimate!!Population 18 to 24 years',
 'Total!!Margin of Error!!Population 18 to 24 years',
 'Total!!Estimate!!Less than high school graduate',
 'Total!!Margin of Error!!Less than high school graduate',
 'Total!!Estimate!!High school graduate (includes equivalency)',
 'Total!!Margin of Error!!High school graduate (includes equivalency)',
 "Total!!Estimate!!Some college or associate's degree",
 "Total!!Margin of Error!!Some college or associate's degree",
 "Total!!Estimate!!Bachelor's degree or higher",
 "Total!!Margin of Error!!Bachelor's degree or higher",
 'Total!!Estimate!!Population 25 years and over',
 'Total!!Margin of Error!!Population 25 years and over',
 'Total!!Estimate!!Less than 9th grade',
 'Total!!Margin of Error!!Less than 9th grade',
 'Total!!Estimate!!9th to 12th grade, no diploma',
 'Total!!Margin of Error!!9th to 12th grade, no diploma',
 'Total!!Estimate!!High school graduate (includes equivalency).1',
 'Total!!Margin of Error!!High school graduate (includes equivalency).1',
 'Total!!Estimate!!Some college, no degree',
 'Total!!Margin of Error!!Some college, no degree',
 "Total!!Estimate!!Associate's degree",
 "Total!!Margin of Error!!Associate's degree",
 "Total!!Estimate!!Bachelor's degree",
 "Total!!Margin of Error!!Bachelor's degree",
 'Total!!Estimate!!Graduate or professional degree',
 'Total!!Margin of Error!!Graduate or professional degree',
 'Total!!Estimate!!Percent high school graduate or higher',
 'Total!!Margin of Error!!Percent high school graduate or higher',
 "Total!!Estimate!!Percent bachelor's degree or higher",
 "Total!!Margin of Error!!Percent bachelor's degree or higher",
 'Total!!Estimate!!Population 25 to 34 years',
 'Total!!Margin of Error!!Population 25 to 34 years',
 'Total!!Estimate!!High school graduate or higher',
 'Total!!Margin of Error!!High school graduate or higher',
 "Total!!Estimate!!Bachelor's degree or higher.1",
 "Total!!Margin of Error!!Bachelor's degree or higher.1",
 'Total!!Estimate!!Population 35 to 44 years',
 'Total!!Margin of Error!!Population 35 to 44 years',
 'Total!!Estimate!!High school graduate or higher.1',
 'Total!!Margin of Error!!High school graduate or higher.1',
 "Total!!Estimate!!Bachelor's degree or higher.2",
 "Total!!Margin of Error!!Bachelor's degree or higher.2",
 'Total!!Estimate!!Population 45 to 64 years',
 'Total!!Margin of Error!!Population 45 to 64 years',
 'Total!!Estimate!!High school graduate or higher.2',
 'Total!!Margin of Error!!High school graduate or higher.2',
 "Total!!Estimate!!Bachelor's degree or higher.3",
 "Total!!Margin of Error!!Bachelor's degree or higher.3",
 'Total!!Estimate!!Population 65 years and over',
 'Total!!Margin of Error!!Population 65 years and over',
 'Total!!Estimate!!High school graduate or higher.3',
 'Total!!Margin of Error!!High school graduate or higher.3',
 "Total!!Estimate!!Bachelor's degree or higher.4",
 "Total!!Margin of Error!!Bachelor's degree or higher.4",
 'Total!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Total!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Total!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 'Total!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 "Total!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Total!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Total!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 "Total!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 'Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Total!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Less than high school graduate',
 'Total!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Less than high school graduate',
 'Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!High school graduate (includes equivalency)',
 'Total!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!High school graduate (includes equivalency)',
 "Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Some college or associate's degree",
 "Total!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Some college or associate's degree",
 "Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Bachelor's degree",
 "Total!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Bachelor's degree",
 'Total!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Graduate or professional degree',
 'Total!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Graduate or professional degree',
 'Total!!Estimate!!PERCENT IMPUTED!!Educational attainment',
 'Total!!Margin of Error!!PERCENT IMPUTED!!Educational attainment',
 'Male!!Estimate!!Population 18 to 24 years',
 'Male!!Margin of Error!!Population 18 to 24 years',
 'Male!!Estimate!!Less than high school graduate',
 'Male!!Margin of Error!!Less than high school graduate',
 'Male!!Estimate!!High school graduate (includes equivalency)',
 'Male!!Margin of Error!!High school graduate (includes equivalency)',
 "Male!!Estimate!!Some college or associate's degree",
 "Male!!Margin of Error!!Some college or associate's degree",
 "Male!!Estimate!!Bachelor's degree or higher",
 "Male!!Margin of Error!!Bachelor's degree or higher",
 'Male!!Estimate!!Population 25 years and over',
 'Male!!Margin of Error!!Population 25 years and over',
 'Male!!Estimate!!Less than 9th grade',
 'Male!!Margin of Error!!Less than 9th grade',
 'Male!!Estimate!!9th to 12th grade, no diploma',
 'Male!!Margin of Error!!9th to 12th grade, no diploma',
 'Male!!Estimate!!High school graduate (includes equivalency).1',
 'Male!!Margin of Error!!High school graduate (includes equivalency).1',
 'Male!!Estimate!!Some college, no degree',
 'Male!!Margin of Error!!Some college, no degree',
 "Male!!Estimate!!Associate's degree",
 "Male!!Margin of Error!!Associate's degree",
 "Male!!Estimate!!Bachelor's degree",
 "Male!!Margin of Error!!Bachelor's degree",
 'Male!!Estimate!!Graduate or professional degree',
 'Male!!Margin of Error!!Graduate or professional degree',
 'Male!!Estimate!!Percent high school graduate or higher',
 'Male!!Margin of Error!!Percent high school graduate or higher',
 "Male!!Estimate!!Percent bachelor's degree or higher",
 "Male!!Margin of Error!!Percent bachelor's degree or higher",
 'Male!!Estimate!!Population 25 to 34 years',
 'Male!!Margin of Error!!Population 25 to 34 years',
 'Male!!Estimate!!High school graduate or higher',
 'Male!!Margin of Error!!High school graduate or higher',
 "Male!!Estimate!!Bachelor's degree or higher.1",
 "Male!!Margin of Error!!Bachelor's degree or higher.1",
 'Male!!Estimate!!Population 35 to 44 years',
 'Male!!Margin of Error!!Population 35 to 44 years',
 'Male!!Estimate!!High school graduate or higher.1',
 'Male!!Margin of Error!!High school graduate or higher.1',
 "Male!!Estimate!!Bachelor's degree or higher.2",
 "Male!!Margin of Error!!Bachelor's degree or higher.2",
 'Male!!Estimate!!Population 45 to 64 years',
 'Male!!Margin of Error!!Population 45 to 64 years',
 'Male!!Estimate!!High school graduate or higher.2',
 'Male!!Margin of Error!!High school graduate or higher.2',
 "Male!!Estimate!!Bachelor's degree or higher.3",
 "Male!!Margin of Error!!Bachelor's degree or higher.3",
 'Male!!Estimate!!Population 65 years and over',
 'Male!!Margin of Error!!Population 65 years and over',
 'Male!!Estimate!!High school graduate or higher.3',
 'Male!!Margin of Error!!High school graduate or higher.3',
 "Male!!Estimate!!Bachelor's degree or higher.4",
 "Male!!Margin of Error!!Bachelor's degree or higher.4",
 'Male!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Male!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Male!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 'Male!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 "Male!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Male!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Male!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 "Male!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 'Male!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Male!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Male!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Less than high school graduate',
 'Male!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Less than high school graduate',
 'Male!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!High school graduate (includes equivalency)',
 'Male!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!High school graduate (includes equivalency)',
 "Male!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Some college or associate's degree",
 "Male!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Some college or associate's degree",
 "Male!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Bachelor's degree",
 "Male!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Bachelor's degree",
 'Male!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Graduate or professional degree',
 'Male!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Graduate or professional degree',
 'Male!!Estimate!!PERCENT IMPUTED!!Educational attainment',
 'Male!!Margin of Error!!PERCENT IMPUTED!!Educational attainment',
 'Female!!Estimate!!Population 18 to 24 years',
 'Female!!Margin of Error!!Population 18 to 24 years',
 'Female!!Estimate!!Less than high school graduate',
 'Female!!Margin of Error!!Less than high school graduate',
 'Female!!Estimate!!High school graduate (includes equivalency)',
 'Female!!Margin of Error!!High school graduate (includes equivalency)',
 "Female!!Estimate!!Some college or associate's degree",
 "Female!!Margin of Error!!Some college or associate's degree",
 "Female!!Estimate!!Bachelor's degree or higher",
 "Female!!Margin of Error!!Bachelor's degree or higher",
 'Female!!Estimate!!Population 25 years and over',
 'Female!!Margin of Error!!Population 25 years and over',
 'Female!!Estimate!!Less than 9th grade',
 'Female!!Margin of Error!!Less than 9th grade',
 'Female!!Estimate!!9th to 12th grade, no diploma',
 'Female!!Margin of Error!!9th to 12th grade, no diploma',
 'Female!!Estimate!!High school graduate (includes equivalency).1',
 'Female!!Margin of Error!!High school graduate (includes equivalency).1',
 'Female!!Estimate!!Some college, no degree',
 'Female!!Margin of Error!!Some college, no degree',
 "Female!!Estimate!!Associate's degree",
 "Female!!Margin of Error!!Associate's degree",
 "Female!!Estimate!!Bachelor's degree",
 "Female!!Margin of Error!!Bachelor's degree",
 'Female!!Estimate!!Graduate or professional degree',
 'Female!!Margin of Error!!Graduate or professional degree',
 'Female!!Estimate!!Percent high school graduate or higher',
 'Female!!Margin of Error!!Percent high school graduate or higher',
 "Female!!Estimate!!Percent bachelor's degree or higher",
 "Female!!Margin of Error!!Percent bachelor's degree or higher",
 'Female!!Estimate!!Population 25 to 34 years',
 'Female!!Margin of Error!!Population 25 to 34 years',
 'Female!!Estimate!!High school graduate or higher',
 'Female!!Margin of Error!!High school graduate or higher',
 "Female!!Estimate!!Bachelor's degree or higher.1",
 "Female!!Margin of Error!!Bachelor's degree or higher.1",
 'Female!!Estimate!!Population 35 to 44 years',
 'Female!!Margin of Error!!Population 35 to 44 years',
 'Female!!Estimate!!High school graduate or higher.1',
 'Female!!Margin of Error!!High school graduate or higher.1',
 "Female!!Estimate!!Bachelor's degree or higher.2",
 "Female!!Margin of Error!!Bachelor's degree or higher.2",
 'Female!!Estimate!!Population 45 to 64 years',
 'Female!!Margin of Error!!Population 45 to 64 years',
 'Female!!Estimate!!High school graduate or higher.2',
 'Female!!Margin of Error!!High school graduate or higher.2',
 "Female!!Estimate!!Bachelor's degree or higher.3",
 "Female!!Margin of Error!!Bachelor's degree or higher.3",
 'Female!!Estimate!!Population 65 years and over',
 'Female!!Margin of Error!!Population 65 years and over',
 'Female!!Estimate!!High school graduate or higher.3',
 'Female!!Margin of Error!!High school graduate or higher.3',
 "Female!!Estimate!!Bachelor's degree or higher.4",
 "Female!!Margin of Error!!Bachelor's degree or higher.4",
 'Female!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Female!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Female!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 'Female!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 "Female!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Female!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Female!!Estimate!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 "Female!!Margin of Error!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 'Female!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Female!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Female!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Less than high school graduate',
 'Female!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Less than high school graduate',
 'Female!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!High school graduate (includes equivalency)',
 'Female!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!High school graduate (includes equivalency)',
 "Female!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Some college or associate's degree",
 "Female!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Some college or associate's degree",
 "Female!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Bachelor's degree",
 "Female!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Bachelor's degree",
 'Female!!Estimate!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Graduate or professional degree',
 'Female!!Margin of Error!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2012 INFLATION-ADJUSTED DOLLARS)!!Graduate or professional degree',
 'Female!!Estimate!!PERCENT IMPUTED!!Educational attainment',
 'Female!!Margin of Error!!PERCENT IMPUTED!!Educational attainment']

In [2]:
df_edu = pd.read_csv('data/2016/2016-Edu/ACSST5Y2016.S1501_data_with_overlays_2020-01-19T112805.csv',
                         header=1, low_memory=False)
df_age_sex = pd.read_csv('data/2016/2016-Age/ACSST5Y2016.S0101_data_with_overlays_2020-01-19T114609.csv',
                             header=1, low_memory=False)
df_race = pd.read_csv('data/2016/2016-Race/ACSDP5Y2016.DP05_data_with_overlays_2020-01-19T114033.csv',
                          header=1, low_memory=False)
df_income = pd.read_csv('data/2016/2016-Income-2/ACSST5Y2016.S1901_data_with_overlays_2020-01-19T114923.csv',
                            header=1, low_memory=False)

In [7]:
len(df_race.columns.tolist())

338

In [6]:
df_race.columns.tolist()

['id',
 'Geographic Area Name',
 'Estimate!!SEX AND AGE!!Total population',
 'Margin of Error!!SEX AND AGE!!Total population',
 'Percent!!SEX AND AGE!!Total population',
 'Percent Margin of Error!!SEX AND AGE!!Total population',
 'Estimate!!SEX AND AGE!!Total population!!Male',
 'Margin of Error!!SEX AND AGE!!Total population!!Male',
 'Percent!!SEX AND AGE!!Total population!!Male',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Male',
 'Estimate!!SEX AND AGE!!Total population!!Female',
 'Margin of Error!!SEX AND AGE!!Total population!!Female',
 'Percent!!SEX AND AGE!!Total population!!Female',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Female',
 'Estimate!!SEX AND AGE!!Under 5 years',
 'Margin of Error!!SEX AND AGE!!Under 5 years',
 'Percent!!SEX AND AGE!!Under 5 years',
 'Percent Margin of Error!!SEX AND AGE!!Under 5 years',
 'Estimate!!SEX AND AGE!!5 to 9 years',
 'Margin of Error!!SEX AND AGE!!5 to 9 years',
 'Percent!!SEX AND AGE!!5 to 9 years',
 'Percent Margin of Error!!SEX AND AGE!!5 to 9 years',
 'Estimate!!SEX AND AGE!!10 to 14 years',
 'Margin of Error!!SEX AND AGE!!10 to 14 years',
 'Percent!!SEX AND AGE!!10 to 14 years',
 'Percent Margin of Error!!SEX AND AGE!!10 to 14 years',
 'Estimate!!SEX AND AGE!!15 to 19 years',
 'Margin of Error!!SEX AND AGE!!15 to 19 years',
 'Percent!!SEX AND AGE!!15 to 19 years',
 'Percent Margin of Error!!SEX AND AGE!!15 to 19 years',
 'Estimate!!SEX AND AGE!!20 to 24 years',
 'Margin of Error!!SEX AND AGE!!20 to 24 years',
 'Percent!!SEX AND AGE!!20 to 24 years',
 'Percent Margin of Error!!SEX AND AGE!!20 to 24 years',
 'Estimate!!SEX AND AGE!!25 to 34 years',
 'Margin of Error!!SEX AND AGE!!25 to 34 years',
 'Percent!!SEX AND AGE!!25 to 34 years',
 'Percent Margin of Error!!SEX AND AGE!!25 to 34 years',
 'Estimate!!SEX AND AGE!!35 to 44 years',
 'Margin of Error!!SEX AND AGE!!35 to 44 years',
 'Percent!!SEX AND AGE!!35 to 44 years',
 'Percent Margin of Error!!SEX AND AGE!!35 to 44 years',
 'Estimate!!SEX AND AGE!!45 to 54 years',
 'Margin of Error!!SEX AND AGE!!45 to 54 years',
 'Percent!!SEX AND AGE!!45 to 54 years',
 'Percent Margin of Error!!SEX AND AGE!!45 to 54 years',
 'Estimate!!SEX AND AGE!!55 to 59 years',
 'Margin of Error!!SEX AND AGE!!55 to 59 years',
 'Percent!!SEX AND AGE!!55 to 59 years',
 'Percent Margin of Error!!SEX AND AGE!!55 to 59 years',
 'Estimate!!SEX AND AGE!!60 to 64 years',
 'Margin of Error!!SEX AND AGE!!60 to 64 years',
 'Percent!!SEX AND AGE!!60 to 64 years',
 'Percent Margin of Error!!SEX AND AGE!!60 to 64 years',
 'Estimate!!SEX AND AGE!!65 to 74 years',
 'Margin of Error!!SEX AND AGE!!65 to 74 years',
 'Percent!!SEX AND AGE!!65 to 74 years',
 'Percent Margin of Error!!SEX AND AGE!!65 to 74 years',
 'Estimate!!SEX AND AGE!!75 to 84 years',
 'Margin of Error!!SEX AND AGE!!75 to 84 years',
 'Percent!!SEX AND AGE!!75 to 84 years',
 'Percent Margin of Error!!SEX AND AGE!!75 to 84 years',
 'Estimate!!SEX AND AGE!!85 years and over',
 'Margin of Error!!SEX AND AGE!!85 years and over',
 'Percent!!SEX AND AGE!!85 years and over',
 'Percent Margin of Error!!SEX AND AGE!!85 years and over',
 'Estimate!!SEX AND AGE!!Median age (years)',
 'Margin of Error!!SEX AND AGE!!Median age (years)',
 'Percent!!SEX AND AGE!!Median age (years)',
 'Percent Margin of Error!!SEX AND AGE!!Median age (years)',
 'Estimate!!SEX AND AGE!!18 years and over',
 'Margin of Error!!SEX AND AGE!!18 years and over',
 'Percent!!SEX AND AGE!!18 years and over',
 'Percent Margin of Error!!SEX AND AGE!!18 years and over',
 'Estimate!!SEX AND AGE!!21 years and over',
 'Margin of Error!!SEX AND AGE!!21 years and over',
 'Percent!!SEX AND AGE!!21 years and over',
 'Percent Margin of Error!!SEX AND AGE!!21 years and over',
 'Estimate!!SEX AND AGE!!62 years and over',
 'Margin of Error!!SEX AND AGE!!62 years and over',
 'Percent!!SEX AND AGE!!62 years and over',
 'Percent Margin of Error!!SEX AND AGE!!62 years and over',
 'Estimate!!SEX AND AGE!!65 years and over',
 'Margin of Error!!SEX AND AGE!!65 years and over',
 'Percent!!SEX AND AGE!!65 years and over',
 'Percent Margin of Error!!SEX AND AGE!!65 years and over',
 'Estimate!!SEX AND AGE!!18 years and over.1',
 'Margin of Error!!SEX AND AGE!!18 years and over.1',
 'Percent!!SEX AND AGE!!18 years and over.1',
 'Percent Margin of Error!!SEX AND AGE!!18 years and over.1',
 'Estimate!!SEX AND AGE!!18 years and over!!Male',
 'Margin of Error!!SEX AND AGE!!18 years and over!!Male',
 'Percent!!SEX AND AGE!!18 years and over!!Male',
 'Percent Margin of Error!!SEX AND AGE!!18 years and over!!Male',
 'Estimate!!SEX AND AGE!!18 years and over!!Female',
 'Margin of Error!!SEX AND AGE!!18 years and over!!Female',
 'Percent!!SEX AND AGE!!18 years and over!!Female',
 'Percent Margin of Error!!SEX AND AGE!!18 years and over!!Female',
 'Estimate!!SEX AND AGE!!65 years and over.1',
 'Margin of Error!!SEX AND AGE!!65 years and over.1',
 'Percent!!SEX AND AGE!!65 years and over.1',
 'Percent Margin of Error!!SEX AND AGE!!65 years and over.1',
 'Estimate!!SEX AND AGE!!65 years and over!!Male',
 'Margin of Error!!SEX AND AGE!!65 years and over!!Male',
 'Percent!!SEX AND AGE!!65 years and over!!Male',
 'Percent Margin of Error!!SEX AND AGE!!65 years and over!!Male',
 'Estimate!!SEX AND AGE!!65 years and over!!Female',
 'Margin of Error!!SEX AND AGE!!65 years and over!!Female',
 'Percent!!SEX AND AGE!!65 years and over!!Female',
 'Percent Margin of Error!!SEX AND AGE!!65 years and over!!Female',
 'Estimate!!RACE!!Total population',
 'Margin of Error!!RACE!!Total population',
 'Percent!!RACE!!Total population',
 'Percent Margin of Error!!RACE!!Total population',
 'Estimate!!RACE!!Total population!!One race',
 'Margin of Error!!RACE!!Total population!!One race',
 'Percent!!RACE!!Total population!!One race',
 'Percent Margin of Error!!RACE!!Total population!!One race',
 'Estimate!!RACE!!Total population!!Two or more races',
 'Margin of Error!!RACE!!Total population!!Two or more races',
 'Percent!!RACE!!Total population!!Two or more races',
 'Percent Margin of Error!!RACE!!Total population!!Two or more races',
 'Estimate!!RACE!!One race',
 'Margin of Error!!RACE!!One race',
 'Percent!!RACE!!One race',
 'Percent Margin of Error!!RACE!!One race',
 'Estimate!!RACE!!One race!!White',
 'Margin of Error!!RACE!!One race!!White',
 'Percent!!RACE!!One race!!White',
 'Percent Margin of Error!!RACE!!One race!!White',
 'Estimate!!RACE!!One race!!Black or African American',
 'Margin of Error!!RACE!!One race!!Black or African American',
 'Percent!!RACE!!One race!!Black or African American',
 'Percent Margin of Error!!RACE!!One race!!Black or African American',
 'Estimate!!RACE!!One race!!American Indian and Alaska Native',
 'Margin of Error!!RACE!!One race!!American Indian and Alaska Native',
 'Percent!!RACE!!One race!!American Indian and Alaska Native',
 'Percent Margin of Error!!RACE!!One race!!American Indian and Alaska Native',
 'Estimate!!RACE!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Percent!!RACE!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Percent Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Estimate!!RACE!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Percent!!RACE!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Percent Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Estimate!!RACE!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Percent!!RACE!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Percent Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Estimate!!RACE!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Percent!!RACE!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Percent Margin of Error!!RACE!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Estimate!!RACE!!One race!!Asian',
 'Margin of Error!!RACE!!One race!!Asian',
 'Percent!!RACE!!One race!!Asian',
 'Percent Margin of Error!!RACE!!One race!!Asian',
 'Estimate!!RACE!!One race!!Asian!!Asian Indian',
 'Margin of Error!!RACE!!One race!!Asian!!Asian Indian',
 'Percent!!RACE!!One race!!Asian!!Asian Indian',
 'Percent Margin of Error!!RACE!!One race!!Asian!!Asian Indian',
 'Estimate!!RACE!!One race!!Asian!!Chinese',
 'Margin of Error!!RACE!!One race!!Asian!!Chinese',
 'Percent!!RACE!!One race!!Asian!!Chinese',
 'Percent Margin of Error!!RACE!!One race!!Asian!!Chinese',
 'Estimate!!RACE!!One race!!Asian!!Filipino',
 'Margin of Error!!RACE!!One race!!Asian!!Filipino',
 'Percent!!RACE!!One race!!Asian!!Filipino',
 'Percent Margin of Error!!RACE!!One race!!Asian!!Filipino',
 'Estimate!!RACE!!One race!!Asian!!Japanese',
 'Margin of Error!!RACE!!One race!!Asian!!Japanese',
 'Percent!!RACE!!One race!!Asian!!Japanese',
 'Percent Margin of Error!!RACE!!One race!!Asian!!Japanese',
 'Estimate!!RACE!!One race!!Asian!!Korean',
 'Margin of Error!!RACE!!One race!!Asian!!Korean',
 'Percent!!RACE!!One race!!Asian!!Korean',
 'Percent Margin of Error!!RACE!!One race!!Asian!!Korean',
 'Estimate!!RACE!!One race!!Asian!!Vietnamese',
 'Margin of Error!!RACE!!One race!!Asian!!Vietnamese',
 'Percent!!RACE!!One race!!Asian!!Vietnamese',
 'Percent Margin of Error!!RACE!!One race!!Asian!!Vietnamese',
 'Estimate!!RACE!!One race!!Asian!!Other Asian',
 'Margin of Error!!RACE!!One race!!Asian!!Other Asian',
 'Percent!!RACE!!One race!!Asian!!Other Asian',
 'Percent Margin of Error!!RACE!!One race!!Asian!!Other Asian',
 'Estimate!!RACE!!One race!!Native Hawaiian and Other Pacific Islander',
 'Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander',
 'Percent!!RACE!!One race!!Native Hawaiian and Other Pacific Islander',
 'Percent Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander',
 'Estimate!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Percent!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Percent Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Estimate!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Percent!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Percent Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Estimate!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Percent!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Percent Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Estimate!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Percent!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Percent Margin of Error!!RACE!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Estimate!!RACE!!One race!!Some other race',
 'Margin of Error!!RACE!!One race!!Some other race',
 'Percent!!RACE!!One race!!Some other race',
 'Percent Margin of Error!!RACE!!One race!!Some other race',
 'Estimate!!RACE!!Two or more races',
 'Margin of Error!!RACE!!Two or more races',
 'Percent!!RACE!!Two or more races',
 'Percent Margin of Error!!RACE!!Two or more races',
 'Estimate!!RACE!!Two or more races!!White and Black or African American',
 'Margin of Error!!RACE!!Two or more races!!White and Black or African American',
 'Percent!!RACE!!Two or more races!!White and Black or African American',
 'Percent Margin of Error!!RACE!!Two or more races!!White and Black or African American',
 'Estimate!!RACE!!Two or more races!!White and American Indian and Alaska Native',
 'Margin of Error!!RACE!!Two or more races!!White and American Indian and Alaska Native',
 'Percent!!RACE!!Two or more races!!White and American Indian and Alaska Native',
 'Percent Margin of Error!!RACE!!Two or more races!!White and American Indian and Alaska Native',
 'Estimate!!RACE!!Two or more races!!White and Asian',
 'Margin of Error!!RACE!!Two or more races!!White and Asian',
 'Percent!!RACE!!Two or more races!!White and Asian',
 'Percent Margin of Error!!RACE!!Two or more races!!White and Asian',
 'Estimate!!RACE!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Margin of Error!!RACE!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Percent!!RACE!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Percent Margin of Error!!RACE!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Estimate!!RACE!!Race alone or in combination with one or more other races!!Total population',
 'Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population',
 'Percent!!RACE!!Race alone or in combination with one or more other races!!Total population',
 'Percent Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population',
 'Estimate!!RACE!!Race alone or in combination with one or more other races!!Total population!!White',
 'Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!White',
 'Percent!!RACE!!Race alone or in combination with one or more other races!!Total population!!White',
 'Percent Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!White',
 'Estimate!!RACE!!Race alone or in combination with one or more other races!!Total population!!Black or African American',
 'Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Black or African American',
 'Percent!!RACE!!Race alone or in combination with one or more other races!!Total population!!Black or African American',
 'Percent Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Black or African American',
 'Estimate!!RACE!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native',
 'Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native',
 'Percent!!RACE!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native',
 'Percent Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native',
 'Estimate!!RACE!!Race alone or in combination with one or more other races!!Total population!!Asian',
 'Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Asian',
 'Percent!!RACE!!Race alone or in combination with one or more other races!!Total population!!Asian',
 'Percent Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Asian',
 'Estimate!!RACE!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander',
 'Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander',
 'Percent!!RACE!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander',
 'Percent Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander',
 'Estimate!!RACE!!Race alone or in combination with one or more other races!!Total population!!Some other race',
 'Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Some other race',
 'Percent!!RACE!!Race alone or in combination with one or more other races!!Total population!!Some other race',
 'Percent Margin of Error!!RACE!!Race alone or in combination with one or more other races!!Total population!!Some other race',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population',
 'Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population',
 'Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)',
 'Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)',
 'Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican',
 'Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican',
 'Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican',
 'Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican',
 'Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban',
 'Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban',
 'Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino',
 'Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino',
 'Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino',
 'Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino',
 'Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino',
 'Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino',
 'Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone',

In [5]:
df_income.columns.tolist()

['id',
 'Geographic Area Name',
 'Households!!Estimate!!Total',
 'Households!!Margin of Error!!Total',
 'Households!!Estimate!!Less than $10,000',
 'Households!!Margin of Error!!Less than $10,000',
 'Households!!Estimate!!$10,000 to $14,999',
 'Households!!Margin of Error!!$10,000 to $14,999',
 'Households!!Estimate!!$15,000 to $24,999',
 'Households!!Margin of Error!!$15,000 to $24,999',
 'Households!!Estimate!!$25,000 to $34,999',
 'Households!!Margin of Error!!$25,000 to $34,999',
 'Households!!Estimate!!$35,000 to $49,999',
 'Households!!Margin of Error!!$35,000 to $49,999',
 'Households!!Estimate!!$50,000 to $74,999',
 'Households!!Margin of Error!!$50,000 to $74,999',
 'Households!!Estimate!!$75,000 to $99,999',
 'Households!!Margin of Error!!$75,000 to $99,999',
 'Households!!Estimate!!$100,000 to $149,999',
 'Households!!Margin of Error!!$100,000 to $149,999',
 'Households!!Estimate!!$150,000 to $199,999',
 'Households!!Margin of Error!!$150,000 to $199,999',
 'Households!!Estimate!!$200,000 or more',
 'Households!!Margin of Error!!$200,000 or more',
 'Households!!Estimate!!Median income (dollars)',
 'Households!!Margin of Error!!Median income (dollars)',
 'Households!!Estimate!!Mean income (dollars)',
 'Households!!Margin of Error!!Mean income (dollars)',
 'Households!!Estimate!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Households!!Margin of Error!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Households!!Estimate!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Households!!Margin of Error!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Households!!Estimate!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Households!!Margin of Error!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Families!!Estimate!!Total',
 'Families!!Margin of Error!!Total',
 'Families!!Estimate!!Less than $10,000',
 'Families!!Margin of Error!!Less than $10,000',
 'Families!!Estimate!!$10,000 to $14,999',
 'Families!!Margin of Error!!$10,000 to $14,999',
 'Families!!Estimate!!$15,000 to $24,999',
 'Families!!Margin of Error!!$15,000 to $24,999',
 'Families!!Estimate!!$25,000 to $34,999',
 'Families!!Margin of Error!!$25,000 to $34,999',
 'Families!!Estimate!!$35,000 to $49,999',
 'Families!!Margin of Error!!$35,000 to $49,999',
 'Families!!Estimate!!$50,000 to $74,999',
 'Families!!Margin of Error!!$50,000 to $74,999',
 'Families!!Estimate!!$75,000 to $99,999',
 'Families!!Margin of Error!!$75,000 to $99,999',
 'Families!!Estimate!!$100,000 to $149,999',
 'Families!!Margin of Error!!$100,000 to $149,999',
 'Families!!Estimate!!$150,000 to $199,999',
 'Families!!Margin of Error!!$150,000 to $199,999',
 'Families!!Estimate!!$200,000 or more',
 'Families!!Margin of Error!!$200,000 or more',
 'Families!!Estimate!!Median income (dollars)',
 'Families!!Margin of Error!!Median income (dollars)',
 'Families!!Estimate!!Mean income (dollars)',
 'Families!!Margin of Error!!Mean income (dollars)',
 'Families!!Estimate!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Families!!Margin of Error!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Families!!Estimate!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Families!!Margin of Error!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Families!!Estimate!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Families!!Margin of Error!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Married-couple families!!Estimate!!Total',
 'Married-couple families!!Margin of Error!!Total',
 'Married-couple families!!Estimate!!Less than $10,000',
 'Married-couple families!!Margin of Error!!Less than $10,000',
 'Married-couple families!!Estimate!!$10,000 to $14,999',
 'Married-couple families!!Margin of Error!!$10,000 to $14,999',
 'Married-couple families!!Estimate!!$15,000 to $24,999',
 'Married-couple families!!Margin of Error!!$15,000 to $24,999',
 'Married-couple families!!Estimate!!$25,000 to $34,999',
 'Married-couple families!!Margin of Error!!$25,000 to $34,999',
 'Married-couple families!!Estimate!!$35,000 to $49,999',
 'Married-couple families!!Margin of Error!!$35,000 to $49,999',
 'Married-couple families!!Estimate!!$50,000 to $74,999',
 'Married-couple families!!Margin of Error!!$50,000 to $74,999',
 'Married-couple families!!Estimate!!$75,000 to $99,999',
 'Married-couple families!!Margin of Error!!$75,000 to $99,999',
 'Married-couple families!!Estimate!!$100,000 to $149,999',
 'Married-couple families!!Margin of Error!!$100,000 to $149,999',
 'Married-couple families!!Estimate!!$150,000 to $199,999',
 'Married-couple families!!Margin of Error!!$150,000 to $199,999',
 'Married-couple families!!Estimate!!$200,000 or more',
 'Married-couple families!!Margin of Error!!$200,000 or more',
 'Married-couple families!!Estimate!!Median income (dollars)',
 'Married-couple families!!Margin of Error!!Median income (dollars)',
 'Married-couple families!!Estimate!!Mean income (dollars)',
 'Married-couple families!!Margin of Error!!Mean income (dollars)',
 'Married-couple families!!Estimate!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Married-couple families!!Margin of Error!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Married-couple families!!Estimate!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Married-couple families!!Margin of Error!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Married-couple families!!Estimate!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Married-couple families!!Margin of Error!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Nonfamily households!!Estimate!!Total',
 'Nonfamily households!!Margin of Error!!Total',
 'Nonfamily households!!Estimate!!Less than $10,000',
 'Nonfamily households!!Margin of Error!!Less than $10,000',
 'Nonfamily households!!Estimate!!$10,000 to $14,999',
 'Nonfamily households!!Margin of Error!!$10,000 to $14,999',
 'Nonfamily households!!Estimate!!$15,000 to $24,999',
 'Nonfamily households!!Margin of Error!!$15,000 to $24,999',
 'Nonfamily households!!Estimate!!$25,000 to $34,999',
 'Nonfamily households!!Margin of Error!!$25,000 to $34,999',
 'Nonfamily households!!Estimate!!$35,000 to $49,999',
 'Nonfamily households!!Margin of Error!!$35,000 to $49,999',
 'Nonfamily households!!Estimate!!$50,000 to $74,999',
 'Nonfamily households!!Margin of Error!!$50,000 to $74,999',
 'Nonfamily households!!Estimate!!$75,000 to $99,999',
 'Nonfamily households!!Margin of Error!!$75,000 to $99,999',
 'Nonfamily households!!Estimate!!$100,000 to $149,999',
 'Nonfamily households!!Margin of Error!!$100,000 to $149,999',
 'Nonfamily households!!Estimate!!$150,000 to $199,999',
 'Nonfamily households!!Margin of Error!!$150,000 to $199,999',
 'Nonfamily households!!Estimate!!$200,000 or more',
 'Nonfamily households!!Margin of Error!!$200,000 or more',
 'Nonfamily households!!Estimate!!Median income (dollars)',
 'Nonfamily households!!Margin of Error!!Median income (dollars)',
 'Nonfamily households!!Estimate!!Mean income (dollars)',
 'Nonfamily households!!Margin of Error!!Mean income (dollars)',
 'Nonfamily households!!Estimate!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Nonfamily households!!Margin of Error!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Nonfamily households!!Estimate!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Nonfamily households!!Margin of Error!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Nonfamily households!!Estimate!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Nonfamily households!!Margin of Error!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months']

In [2]:
features_2016 = county_info_2016()
features_2018 = county_info_2018()
results_2016 = results_info(2016)

In [6]:
df_results = pd.read_csv('data/countypres_2000-2016.csv')

In [8]:
df_results.loc[df_results['county'] == 'District of Columbia', 'county'] = 'Washington city'

In [3]:
df_results = pd.read_csv('data/countypres_2000-2016.csv')

# delete duplicates
del_index = [49178, 49179, 49180, 49205, 49206, 49207, 49211, 49212,
             49213, 49265, 49266, 49267, 49268, 49269, 49270]
    
df_results.loc[df_results['county'] == 'District of Columbia', 'county'] = 'Washington city'
    
df_results = df_results.drop(del_index)

df_results['County'] = df_results['county'] + ' County, ' + df_results['state'] + ', ' + str(2016)
df = df_results[df_results.year == 2016]
df = df.pivot(index='County', columns='candidate',
                        values=['state', 'candidatevotes']).reset_index()

In [11]:
df_results = pd.read_csv('data/countypres_2000-2016.csv')

# delete duplicates
del_index = [49178, 49179, 49180, 49205, 49206, 49207, 49211, 49212,
             49213, 49265, 49266, 49267, 49268, 49269, 49270]

df_results.loc[df_results['county'] == 'District of Columbia', 'county'] = 'Washington city'

df_results = df_results.drop(del_index)

df_results['County'] = df_results['county'] + ' County, ' + df_results['state'] + ', ' + str(2016)
df = df_results[df_results.year == 2016]
df = df.pivot(index='County', columns='candidate',
                        values=['state', 'candidatevotes']).reset_index()

res = pd.merge(df['County'], pd.DataFrame(df['state']['Donald Trump']),
                left_index=True, right_index=True)
res = pd.merge(res, pd.DataFrame(df['candidatevotes']['Donald Trump']),
                 left_index=True, right_index=True)
res = pd.merge(res, pd.DataFrame(df['candidatevotes']['Hillary Clinton']),
                 left_index=True, right_index=True)
res = pd.merge(res, pd.DataFrame(df['candidatevotes']['Other']),
               left_index=True, right_index=True)
res = res.rename(columns={'Donald Trump_x': 'State',
                            'Donald Trump_y': 'Republican',
                            'Hillary Clinton': 'Democrat'})

In [12]:
res[res.County == 'Washington city County, District of Columbia, 2016']

,County,State,Republican,Democrat,Other
2993,"Washington city County, District of Columbia, ...",District of Columbia,12723,282830,15715

In [13]:
features_2016 = county_info_2016()
#results_2016 = results_info(2016)

In [16]:
features_2016[features_2016.County == 'Washington city, District of Columbia, 2016']

,County,Percent Less than 9th grade,"Percent 9th to 12th grade, no diploma",Percent High school graduate,"Percent Some college, no degree",Percent Associate's degree,Percent Bachelor's degree,Percent Graduate or professional degree,Total population,Median age,Sex ratio (males per 100 females),Male Median age,Female Median age,Percent White,Percent Black or African American,Percent American Indian and Alaska Native,Percent Asian,Percent Hispanic or Latino,Households Median income,Households Mean income
3220,"Washington city, District of Columbia, 2016",4.0,6.0,18.0,13.5,3.1,23.4,32.0,659009,33.8,90.3,33.6,34.0,40.4,48.3,0.3,3.6,10.5,72935,110614

In [11]:
len(results_2016[results_2016['State'] == 'Alaska'])

41

In [ ]:
for y in y_list:
    

X_train, X_test, y_train, y_test = train_test_split(X, y_R)

In [ ]:
pipe_scl_lin = Pipeline([('scl', StandardScaler()), ('lin', LinearRegression())])
pipe_mms_lin = Pipeline([('mms', MinMaxScaler()), ('lin', LinearRegression())])

# Fit the pipelines
pipe_lr.fit(X_train, y_train)

print(pipe_lr.score(X_test, y_test))

pipelines = [pipe_scl_lin, pipe_mms_lin]
pipeline_names = ['Standard Scalar Linear', 'Min Max Linear']

for pipe in pipelines:
    print(pipe)
    pipe.fit(X_train, y_train)

In [ ]:
pipelines = [pipe_scl_lin, pipe_mms_lin]
pipeline_names = ['Standard Scalar Linear','Min Max Linear']

In [ ]:
for pipe in pipelines:
    print(pipe)
    pipe.fit(X_train, y_train)

In [2]:
df_edu_2016 = pd.read_csv('data/2016/ACSST5Y2016-Edu/ACSST5Y2016.S1501_data_with_overlays_2020-01-15T123834.csv', header=1, low_memory=False)
df_edu_2018 = pd.read_csv('data/2018/ACSST5Y2018-Edu/ACSST5Y2018.S1501_data_with_overlays_2020-01-16T122405.csv', header=1, low_memory=False)

df_age_sex_2018 = pd.read_csv('data/2018/ACSST5Y2018-Sex/ACSST5Y2018.S0101_data_with_overlays_2020-01-16T114607.csv', header=1, low_memory=False)

df_race_2018 = pd.read_csv('data/2018/ACSDP5Y2018-Race/ACSDP5Y2018.DP05_data_with_overlays_2020-01-16T115900.csv', header=1, low_memory=False)

In [3]:
edu_2016 = df_edu_2016.columns.tolist()
edu_2018 = df_edu_2018.columns.tolist()

In [7]:
feature_list = []
percent_list = [ele for ele in edu_2016 if "Percent" in ele]
error_list = [ele for ele in percent_list if "Error" in ele]
feature_list = [x for x in percent_list if x not in error_list]

In [62]:
blah = list(set(edu_2016).intersection(edu_2018))
percent_list = [ele for ele in blah if "Percent" in ele]
error_list = [ele for ele in percent_list if "Error" in ele]
feature_list = [x for x in percent_list if x not in error_list]

In [66]:
feature_list.sort()

In [30]:
df_income = pd.read_csv('data/2018/ACSST5Y2018-Income/ACSST5Y2018.S1902_data_with_overlays_2020-01-16T120818.csv', header=1, low_memory=False)

In [2]:
# read in csvs
df_edu = pd.read_csv('data/2016/ACSST5Y2016-Edu/ACSST5Y2016.S1501_data_with_overlays_2020-01-15T123834.csv', header=1, low_memory=False)
df_age_sex = pd.read_csv('data/2016/ACSST5Y2016-Sex/ACSST5Y2016.S0101_data_with_overlays_2020-01-15T131242.csv', header=1, low_memory=False)
df_race = pd.read_csv('data/2016/ACSDP5Y2016-Race/ACSDP5Y2016.DP05_data_with_overlays_2020-01-15T133652.csv', header=1, low_memory=False)
df_income = pd.read_csv('data/2016/ACSST5Y2016-Income/ACSST5Y2016.S1901_data_with_overlays_2020-01-15T140106.csv', header=1, low_memory=False)

In [5]:
# select specific columns
county = df_edu['Geographic Area Name']
edu = df_edu[education_columns]
age_sex = df_age_sex[age_sex_columns_2016]
race = df_race[race_columns_2016]
income = df_income[income_columns_2016]

KeyError: "None of [Index(['Estimate!!Percent!!Population 25 years and over!!Less than 9th grade',\n       'Estimate!!Percent!!Population 25 years and over!!9th to 12th grade, no diploma',\n       'Estimate!!Percent!!Population 25 years and over!!High school graduate (includes equivalency)',\n       'Estimate!!Percent!!Population 25 years and over!!Some college, no degree',\n       'Estimate!!Percent!!Population 25 years and over!!Associate's degree',\n       'Estimate!!Percent!!Population 25 years and over!!Bachelor's degree',\n       'Estimate!!Percent!!Population 25 years and over!!Graduate or professional degree'],\n      dtype='object')] are in the [columns]"

In [ ]:
 # merge dataframes
    df = pd.merge(county, edu, left_index=True, right_index=True)
    df = pd.merge(df, age_sex, left_index=True, right_index=True)
    df = pd.merge(df, race, left_index=True, right_index=True)
    df = pd.merge(df, income, left_index=True, right_index=True)
    
    # rename features
    df = df.rename(columns={"Geographic Area Name": "County",
                   "Percent!!Estimate!!Percent high school graduate or higher": "Percent high school graduate or higher",
                   "Percent!!Estimate!!Percent bachelor's degree or higher": "Percent bachelor's degree or higher",
                   "Percent Males!!Estimate!!Percent high school graduate or higher": "Males Percent high school graduate or higher",
                   "Percent Males!!Estimate!!Percent bachelor's degree or higher": "Males Percent bachelor's degree or higher",
                   "Percent Females!!Estimate!!Percent high school graduate or higher": "Females Percent high school graduate or higher",
                   "Percent Females!!Estimate!!Percent bachelor's degree or higher": "Females Percent bachelor's degree or higher",
                   "Total!!Estimate!!Total population": "Total population",
                   "Total!!Estimate!!SUMMARY INDICATORS!!Median age (years)": "Median age",
                   "Total!!Estimate!!SUMMARY INDICATORS!!Sex ratio (males per 100 females)": "Sex ratio (males per 100 females)",
                   "Male!!Estimate!!SUMMARY INDICATORS!!Median age (years)": "Male Median age",
                   "Female!!Estimate!!SUMMARY INDICATORS!!Median age (years)": "Female Median age",
                   "Percent!!RACE!!One race!!White": "Percent White",
                   "Percent!!RACE!!One race!!Black or African American": "Percent Black or African American",
                   "Percent!!RACE!!One race!!American Indian and Alaska Native": "Percent American Indian and Alaska Native",
                   "Percent!!RACE!!One race!!Asian": "Percent Asian",
                   "Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)": "Percent Hispanic or Latino",
                   "Households!!Estimate!!Median income (dollars)": "Households Median income",
                   "Households!!Estimate!!Mean income (dollars)": "Households Mean income"})
    
    return df

In [9]:
df_edu.columns.tolist().intersection(education_columns)

AttributeError: 'list' object has no attribute 'intersection'

In [10]:
list(set(df_edu.columns.tolist()) & set(education_columns))

[]

In [2]:
df_income_2018 = pd.read_csv('data/2018/ACSST5Y2018-Income/ACSST5Y2018.S1902_data_with_overlays_2020-01-16T120818.csv', header=1, low_memory=False)

In [6]:
income_2016_test = pd.read_csv('data/2016/2016-Income/ACSST5Y2016.S1901_data_with_overlays_2020-01-16T145642.csv', header=1, low_memory=False)
income_2018_test = pd.read_csv('data/2018/2018-Income/ACSST5Y2018.S1901_data_with_overlays_2020-01-16T145642.csv', header=1, low_memory=False)

In [ ]:
income_2016_features = ['Households!!Estimate!!Median income (dollars)', 'Households!!Estimate!!Mean income (dollars)']
income_2018_features = ['Estimate!!Households!!Median income (dollars)', 'Estimate!!Households!!Mean income (dollars)']

In [1]:
import pandas as pd
df_edu = pd.read_csv('data/2016/2016-Edu/ACSST5Y2016.S1501_data_with_overlays_2020-01-19T112805.csv',
                         header=1, low_memory=False)
county = df_edu['Geographic Area Name']

In [2]:
test = county.str.split(',', expand=True)
test = test.rename(columns={0: 'County', 1: 'State'})
test['State'] = test['State'].apply(lambda x: x.strip())
#test['County'] = test['State'].apply(lambda x: x.strip())
county = pd.merge(county, test, left_index=True, right_index=True)

In [3]:
county

,Geographic Area Name,County,State
0,"Wilcox County, Alabama",Wilcox County,Alabama
1,"Winston County, Alabama",Winston County,Alabama
2,"Aleutians East Borough, Alaska",Aleutians East Borough,Alaska
3,"Aleutians West Census Area, Alaska",Aleutians West Census Area,Alaska
4,"Anchorage Municipality, Alaska",Anchorage Municipality,Alaska
...,...,...,...
3216,"Río Grande Municipio, Puerto Rico",Río Grande Municipio,Puerto Rico
3217,"Comerío Municipio, Puerto Rico",Comerío Municipio,Puerto Rico
3218,"San Germán Municipio, Puerto Rico",San Germán Municipio,Puerto Rico
3219,"Bayamón Municipio, Puerto Rico",Bayamón Municipio,Puerto Rico
3220,"Washington city, District of Columbia",Washington city,District of Columbia

In [5]:
county['Geographic Area Name'].apply(lambda row: row + ', County')

0                      Wilcox County, Alabama, County
1                     Winston County, Alabama, County
2              Aleutians East Borough, Alaska, County
3          Aleutians West Census Area, Alaska, County
4              Anchorage Municipality, Alaska, County
                            ...
3216        Río Grande Municipio, Puerto Rico, County
3217           Comerío Municipio, Puerto Rico, County
3218        San Germán Municipio, Puerto Rico, County
3219           Bayamón Municipio, Puerto Rico, County
3220    Washington city, District of Columbia, County
Name: Geographic Area Name, Length: 3221, dtype: object

In [11]:
county['test'] = county['Geographic Area Name'].apply(lambda row: row + ', County' if county['State'] == 'Louisiana' else row)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
county['Geographic Area Name'] = county['Geographic Area Name'].apply(lambda row:row + ', 2016' if )

In [11]:
test.State.unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'Illinois',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Kentucky', 'Louisiana', 'Indiana', 'Iowa', 'Kansas', 'Missouri',
       'Montana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'North Carolina', 'North Dakota',
       'Ohio', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
       'New Mexico', 'New York', 'Tennessee', 'Texas', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Virginia', 'Washington', 'Utah', 'Vermont',
       'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico'],
      dtype=object)

In [13]:
test[test.State == 'Louisiana']

                            0      State
793             Acadia Parish  Louisiana
794              Allen Parish  Louisiana
795          Ascension Parish  Louisiana
796         Assumption Parish  Louisiana
797          Avoyelles Parish  Louisiana
...                       ...        ...
1234           Webster Parish  Louisiana
1235  West Baton Rouge Parish  Louisiana
1236      West Carroll Parish  Louisiana
1237    West Feliciana Parish  Louisiana
1238              Winn Parish  Louisiana

[64 rows x 2 columns]

In [16]:
test[test.State == 'Alabama']

                     0    State
0        Wilcox County  Alabama
1       Winston County  Alabama
121     Autauga County  Alabama
122     Baldwin County  Alabama
123     Barbour County  Alabama
..                 ...      ...
181   Talladega County  Alabama
182  Tallapoosa County  Alabama
183  Tuscaloosa County  Alabama
184      Walker County  Alabama
185  Washington County  Alabama

[67 rows x 2 columns]

In [ ]:
# df.iloc[df['Percent Republican'].idxmax()]
# df.iloc[df['Percent Democrat'].idxmax()]
# df.iloc[df['Percent Other'].idxmax()]